### ISSUE TITLE
question :: duplex communication possible?

### ISSUE THREAD

**Issue by madkote** [kchmck/aiopipe#1]
Hi,
is it possible to create a duplex communication (aka websocket)?

e.g. write and read from pipes on the main processes and do same on child? or is some synchronization required for that task?

thanks!

**Comment by kchmck** [comment]
Just so happens I've been working on that offline. I'll see about buttoning it up and getting it published.

**Comment by kchmck** [comment]
Went ahead and released 0.2 with the new [aioduplex](https://kchmck.github.io/aiopipe/aiopipe/#aiopipe.aioduplex) function.

**Comment by madkote** [comment]
@kchmck great - this functionality is great!

Many Thanks for this library! very appreciated!
